// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::*;
use diesel::sql_types::BigInt;
use diesel::{self, prelude::*};
use ethers::types::{U256, U64};
use schema::blocks;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Queryable, QueryableByName, Debug)]
#[diesel(table_name = blocks)]
pub struct Block {
    pub number: i64,
    pub timestamp: i64,
    pub hash: String,
}

#[derive(QueryableByName, Debug)]
pub struct Count {
    #[diesel(sql_type = BigInt)]
    count: i64,
}
