// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::*;
use diesel::sql_types::BigInt;
use diesel::{self, prelude::*};
use schema::cars;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Queryable, QueryableByName, Debug)]
#[table_name = "cars"]
pub struct Car {
    pub id: i32,
    pub name: String,
    pub model: String,
}

#[derive(QueryableByName,Debug)]
pub struct Count {
    #[sql_type = "BigInt"]
    count: i64,
}
