// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::transactions;
use crate::*;
use diesel::sql_types::BigInt;
use diesel::{self, prelude::*};
use ethers::types::{U256, U64};
use schema::blocks;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Queryable, QueryableByName, Debug)]
#[diesel(table_name = blocks)]
pub struct Block {
    pub number: i64,
    pub timestamp: i64,
    pub hash: String,
}

#[derive(Deserialize, Serialize, Queryable, QueryableByName, Debug)]
#[diesel(table_name = blocks)]
pub struct BlockNumber {
    pub number: i64,
    pub timestamp: i64,
    pub hash: String,
}

#[derive(QueryableByName, Debug)]
pub struct Count {
    #[diesel(sql_type = BigInt)]
    count: i64,
}

#[derive(Deserialize, Serialize, Queryable, QueryableByName, Debug)]
#[diesel(table_name = transactions)]
pub struct Transaction {
    pub hash: String,
    pub value: i128,
    pub position: i16,
    pub sender: String,
    pub receiver: String,
    pub input: String,
    pub block_number: i64
}